create extension if not exists pgcrypto;

create table if not exists public.whatsapp_agent_checkins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null check (char_length(label) between 1 and 120),
  template_name text not null check (template_name ~ '^[a-z0-9_]{1,512}$'),
  template_language text not null default 'en_US' check (char_length(template_language) between 2 and 20),
  cadence text not null default 'daily' check (cadence in ('daily', 'weekly')),
  days_of_week smallint[] not null default array[1,2,3,4,5,6,0]::smallint[],
  local_time time not null default '09:00',
  timezone text not null default 'America/New_York' check (char_length(timezone) between 1 and 80),
  enabled boolean not null default false,
  last_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_agent_checkins_valid_days check (
    cardinality(days_of_week) between 1 and 7
    and days_of_week <@ array[0,1,2,3,4,5,6]::smallint[]
  )
);

create index if not exists whatsapp_agent_checkins_due_idx
  on public.whatsapp_agent_checkins (enabled, local_time)
  where enabled;

alter table public.whatsapp_agent_checkins enable row level security;

drop policy if exists "Owner reads WhatsApp check-ins" on public.whatsapp_agent_checkins;
create policy "Owner reads WhatsApp check-ins"
  on public.whatsapp_agent_checkins for select to authenticated
  using (
    user_id = (select auth.uid())
    and exists (select 1 from public.site_admins a where a.user_id = (select auth.uid()))
  );

drop policy if exists "Owner creates WhatsApp check-ins" on public.whatsapp_agent_checkins;
create policy "Owner creates WhatsApp check-ins"
  on public.whatsapp_agent_checkins for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (select 1 from public.site_admins a where a.user_id = (select auth.uid()))
  );

drop policy if exists "Owner updates WhatsApp check-ins" on public.whatsapp_agent_checkins;
create policy "Owner updates WhatsApp check-ins"
  on public.whatsapp_agent_checkins for update to authenticated
  using (
    user_id = (select auth.uid())
    and exists (select 1 from public.site_admins a where a.user_id = (select auth.uid()))
  )
  with check (
    user_id = (select auth.uid())
    and exists (select 1 from public.site_admins a where a.user_id = (select auth.uid()))
  );

drop policy if exists "Owner deletes WhatsApp check-ins" on public.whatsapp_agent_checkins;
create policy "Owner deletes WhatsApp check-ins"
  on public.whatsapp_agent_checkins for delete to authenticated
  using (
    user_id = (select auth.uid())
    and exists (select 1 from public.site_admins a where a.user_id = (select auth.uid()))
  );

create table if not exists public.whatsapp_agent_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_id uuid references public.whatsapp_agent_checkins(id) on delete set null,
  whatsapp_message_id text unique,
  reply_to_message_id text,
  direction text not null check (direction in ('inbound', 'outbound')),
  message_type text not null default 'text' check (message_type in ('text', 'template', 'status', 'unsupported')),
  phone_hash text not null check (phone_hash ~ '^[0-9a-f]{64}$'),
  body text not null default '' check (char_length(body) <= 12000),
  provider_status text,
  error_code text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '90 days')
);

create index if not exists whatsapp_agent_messages_owner_created_idx
  on public.whatsapp_agent_messages (user_id, created_at desc);
create index if not exists whatsapp_agent_messages_reply_idx
  on public.whatsapp_agent_messages (reply_to_message_id)
  where reply_to_message_id is not null;
create index if not exists whatsapp_agent_messages_expiry_idx
  on public.whatsapp_agent_messages (expires_at);

alter table public.whatsapp_agent_messages enable row level security;

drop policy if exists "Owner reads WhatsApp history" on public.whatsapp_agent_messages;
create policy "Owner reads WhatsApp history"
  on public.whatsapp_agent_messages for select to authenticated
  using (
    user_id = (select auth.uid())
    and exists (select 1 from public.site_admins a where a.user_id = (select auth.uid()))
  );

drop policy if exists "Owner deletes WhatsApp history" on public.whatsapp_agent_messages;
create policy "Owner deletes WhatsApp history"
  on public.whatsapp_agent_messages for delete to authenticated
  using (
    user_id = (select auth.uid())
    and exists (select 1 from public.site_admins a where a.user_id = (select auth.uid()))
  );

revoke all on table public.whatsapp_agent_checkins from anon;
revoke all on table public.whatsapp_agent_messages from anon;
revoke all on table public.whatsapp_agent_checkins from authenticated;
revoke all on table public.whatsapp_agent_messages from authenticated;
grant select, insert, update, delete on table public.whatsapp_agent_checkins to authenticated;
grant select, delete on table public.whatsapp_agent_messages to authenticated;
